### ISSUE TITLE
Error Received While Rendering

### ISSUE THREAD

**Issue by yashunandansureka** [fastass-ez/cloud_rendering_gc#1]
Hi,

I get the following error while rendering. It is rendering but i am not sure if GPU is being used?

Error: Python: Traceback (most recent call last):
  File "/content/drive/MyDrive/BlenderRenders/Res/GPU.py", line 31, in <module>
    enable_gpus("CUDA")
  File "/content/drive/MyDrive/BlenderRenders/Res/GPU.py", line 7, in enable_gpus
    cuda_devices, opencl_devices = cycles_preferences.get_devices()

**Comment by fastass-ez** [comment]
hey, I'm not sure exactly what the issue is so I need to know more. Though
it's going to be a lot more difficult using emails so I suggest u dm me on
discord at fastass#8019

**Comment by L0Fem** [comment]
Hi, 

I put the file blender project in the Blender_CG folder witch is in my google drive. When asking the filename in put it classroom.blend when I lunch the render. It's says no such file or directory. 
I<ve send you a friends request on Discord.

**Comment by merecesarchviz** [comment]
i have the same issue!! any solution?
